import 'package:flutter/material.dart';

import '../settings/app_settings_controller.dart';

class AppStrings {
  static const Map<String, Map<String, String>> _translations = {
    'de': {
      'movie_list_title': 'CineCue',
      'app_brand': 'CineCue',
      'welcome_subtitle':
          'Dein Filmjournal mit smarter Suche, Postern und schnellen Bewertungen.',
      'welcome_note':
          'Die Einrichtung dauert etwa 2 Minuten. Danach kannst du sofort loslegen.',
      'welcome_setup_cta': 'Einrichten',
      'tab_home': 'Home',
      'tab_watched': 'Schon gesehen',
      'tab_discover': 'Eintragen',
      'tab_discover_feed': 'Entdecken',
      'home_title': 'Für dich',
      'home_jump_search': 'Suche',
      'home_popular_title': 'Most Popular',
      'home_greeting_title': 'Hallo, Filmfan',
      'home_greeting_subtitle': 'Suche und trage gesehene Filme schnell ein.',
      'home_search_hint': 'Nach einem Titel suchen...',
      'home_featured_label': 'Empfohlen',
      'home_see_all': 'Alle',
      'drawer_subtitle': 'Schnellzugriff',
      'drawer_genres': 'Genres',
      'drawer_all_genres': 'Alle Genres',
      'drawer_categories': 'Kategorien',
      'drawer_all_categories': 'Alle Kategorien',
      'no_movies_yet': 'Noch keine Filme eingetragen.',
      'add_movie': 'Film hinzufügen',
      'edit_movie': 'Film bearbeiten',
      'save': 'Speichern',
      'title': 'Filmtitel',
      'comment': 'Kommentar',
      'choose_image': 'Eigenes Bild wählen',
      'update_metadata': 'Metadaten laden',
      'personal_rating': 'Deine Bewertung',
      'imdb_rating': 'IMDb',
      'rotten_tomatoes': 'Rotten Tomatoes',
      'year': 'Jahr',
      'genre': 'Genre',
      'director': 'Regie',
      'runtime': 'Laufzeit',
      'watched_on': 'Gesehen am',
      'watch_platform': 'Plattform',
      'select_date': 'Datum wählen',
      'metadata_loading': 'Lade Filmdaten...',
      'metadata_error': 'Keine Daten für diesen Titel gefunden.',
      'metadata_hint': 'Titel eingeben und Metadaten automatisch laden lassen.',
      'metadata_missing_api_key':
          'Bitte OMDb API-Key in den Einstellungen hinterlegen.',
      'metadata_tmdb_poster_only':
          'Poster geladen. Für IMDb/Rotten Tomatoes bitte zusätzlich OMDb-Key eintragen.',
      'no_comment': 'Kein Kommentar',
      'delete': 'Löschen',
      'edit': 'Ändern',
      'rating_desc': 'Bewertung absteigend',
      'rating_asc': 'Bewertung aufsteigend',
      'title_asc': 'Titel A-Z',
      'category_asc': 'Kategorie A-Z',
      'last_watched': 'Zuletzt bewertet',
      'sort_popularity_desc': 'Popularität absteigend',
      'sort_popularity_asc': 'Popularität aufsteigend',
      'sort_title_desc': 'Titel Z-A',
      'settings': 'Einstellungen',
      'dark_mode': 'Dark Mode',
      'dark_mode_desc': 'Aktiviere ein dunkles Farbschema',
      'language': 'Sprache',
      'language_desc': 'Wähle die App-Sprache',
      'notifications': 'Benachrichtigungen',
      'notifications_desc': 'Demnächst verfügbar',
      'privacy_security': 'Datenschutz & Sicherheit',
      'privacy_settings': 'Demnächst verfügbar',
      'help_support': 'Hilfe & Support',
      'contact_us': 'Demnächst verfügbar',
      'app_version': 'App Version',
      'connected_success': 'Erfolgreich verbunden',
      'login_failed': 'Login fehlgeschlagen',
      'signed_out': 'Erfolgreich abgemeldet',
      'no_account_connected': 'Kein Account verbunden',
      'connect': 'Verbinden',
      'disconnect': 'Abmelden',
      'cloud_backup_title': 'Cloud-Backup',
      'cloud_backup_desc':
          'Sichere deine Filme in Google Drive (privater App-Bereich).',
      'cloud_backup_not_connected': 'Kein Google-Konto verbunden',
      'cloud_backup_retention': 'Versionen behalten',
      'cloud_backup_threshold': 'Auto-Backup nach Änderungen',
      'cloud_backup_last_backup': 'Letztes Backup',
      'cloud_backup_pending_changes': 'Offene Änderungen',
      'cloud_backup_never': 'Noch kein Backup',
      'cloud_backup_now': 'Jetzt sichern',
      'cloud_restore_latest': 'Letztes Backup wiederherstellen',
      'cloud_auto_backup': 'Automatisches Backup',
      'cloud_auto_backup_desc':
          'Sichert bei mehreren Änderungen und beim App-Verlassen.',
      'cloud_auto_restore': 'Automatisch beim Start wiederherstellen',
      'cloud_auto_restore_desc':
          'Nur wenn lokal noch keine Filme vorhanden sind.',
      'cloud_restore_confirm_title': 'Backup wiederherstellen?',
      'cloud_restore_confirm_message':
          'Deine lokale Filmliste wird mit dem neuesten Cloud-Backup überschrieben.',
      'cloud_restore_confirm_action': 'Wiederherstellen',
      'cloud_backup_not_signed_in': 'Bitte zuerst mit Google Drive verbinden.',
      'cloud_backup_in_progress': 'Backup läuft bereits.',
      'cloud_backup_db_missing': 'Lokale Datenbank wurde nicht gefunden.',
      'cloud_backup_success': 'Backup erfolgreich hochgeladen.',
      'cloud_backup_failed': 'Backup konnte nicht erstellt werden.',
      'cloud_backup_no_backups': 'Kein Cloud-Backup gefunden.',
      'cloud_backup_integrity_failed':
          'Integritätsprüfung fehlgeschlagen. Restore abgebrochen.',
      'cloud_restore_success': 'Backup erfolgreich wiederhergestellt.',
      'cloud_restore_failed': 'Backup konnte nicht wiederhergestellt werden.',
      'no_image': 'Kein Bild ausgewählt',
      'auto_data': 'Automatische Daten',
      'ratings': 'Ratings',
      'details': 'Details',
      'plot': 'Handlung',
      'select_sort': 'Sortierung',
      'catalog_panel_title': 'Filme entdecken',
      'catalog_panel_desc':
          'Suche nach Filmen und trage sie direkt als gesehen ein.',
      'catalog_search_hint': 'Film suchen (z. B. Hangover)',
      'catalog_preview_hint':
          'Film antippen, Details prüfen und dann eintragen.',
      'catalog_missing_key':
          'Für die Suche brauchst du einen OMDb API-Key in den Einstellungen.',
      'catalog_open_settings': 'Zu den Einstellungen',
      'catalog_prompt': 'Gib mindestens 2 Zeichen ein, um Filme zu suchen.',
      'catalog_searching': 'Suche läuft...',
      'catalog_no_results': 'Keine passenden Filme gefunden.',
      'catalog_add_button': 'Eintragen',
      'catalog_open_details': 'Details',
      'catalog_already_added': 'Schon eingetragen',
      'catalog_year_unknown': 'Jahr unbekannt',
      'catalog_loading_details': 'Lade Filmdetails...',
      'catalog_add_from_details': 'Eintragen',
      'catalog_duplicate_blocked':
          'Der Film ist bereits in deiner Liste und kann nicht doppelt eingetragen werden.',
      'discover_feed_title': 'Film-Inspiration',
      'discover_feed_desc':
          'Beliebte Filme entdecken und direkt in deine Liste übernehmen.',
      'discover_feed_loading': 'Lade Vorschläge...',
      'discover_feed_empty': 'Keine Vorschläge verfügbar.',
      'discover_feed_missing_key':
          'Für Vorschläge trage bitte einen TMDB API-Key in den Einstellungen ein.',
      'discover_feed_offline':
          'Keine Verbindung. Prüfe dein Internet und versuche es erneut.',
      'discover_feed_error': 'Vorschläge konnten gerade nicht geladen werden.',
      'retry': 'Erneut versuchen',
      'watched_search_hint': 'In schon gesehen suchen',
      'seen_panel_title': 'Gesehen',
      'seen_panel_count_suffix': 'Filme',
      'manual_add_movie': 'Manuell hinzufügen',
      'watchlist_title': 'Watchlist',
      'watchlist_empty': 'Deine Watchlist ist noch leer.',
      'watchlist_subtitle': 'Zum Anschauen vorgemerkt',
      'watchlist_added': 'Zur Watchlist hinzugefügt.',
      'mark_as_watched': 'Als gesehen eintragen',
      'watchlist_sort_added': 'Zuletzt hinzugefügt',
      'watchlist_sort_title': 'Titel A-Z',
      'watchlist_sort_rating': 'Bewertung absteigend',
      'category': 'Kategorie',
      'category_hint': 'z. B. Möchte ich nochmal schauen',
      'category_wishlist': 'Möchte ich sehen',
      'category_favorite': 'Fand ich extrem gut',
      'category_rewatch': 'Möchte ich nochmal schauen',
      'category_manage_title': 'Eigene Kategorien',
      'category_manage_desc':
          'Lege eigene Kategorien an. Diese erscheinen in der Filmauswahl und im Filter.',
      'category_new_label': 'Neue Kategorie',
      'category_add': 'Hinzufügen',
      'category_empty': 'Noch keine eigenen Kategorien',
      'setup_wizard_title': 'Einrichtung',
      'setup_intro_title': 'Schnell eingerichtet',
      'setup_intro_desc':
          'In wenigen Minuten lädt die App automatisch Poster und zusätzliche Bewertungen zu deinen Filmen.',
      'setup_intro_local_only':
          'Alles bleibt nur auf deinem Gerät gespeichert.',
      'setup_intro_omdb_info':
          'OMDb liefert Filmdaten sowie IMDb- und Rotten-Tomatoes-Bewertungen.',
      'setup_intro_tmdb_info':
          'TMDB ergänzt Poster, wenn OMDb für einen Titel kein passendes Bild hat.',
      'back': 'Zurück',
      'next': 'Weiter',
      'finish_setup': 'Fertig',
      'setup_done': 'Einrichtung abgeschlossen',
      'metadata_settings_title': 'Filmdaten & Ratings',
      'metadata_setup_title': 'Setup-Assistent',
      'metadata_setup_desc':
          'Richte deine Keys Schritt für Schritt ein. Deine Eingaben bleiben nur in dieser App.',
      'start_setup': 'Einrichtung starten',
      'show_api_keys': 'Keys anzeigen',
      'hide_api_keys': 'Keys ausblenden',
      'setup_step_1_title': '1. OMDb-Key erstellen',
      'setup_step_1_desc':
          'Hier richtest du den OMDb-Key ein, damit Filmdaten und Bewertungen automatisch geladen werden.',
      'setup_step_2_title': '2. Optional: TMDB-Key erstellen',
      'setup_step_2_desc':
          'Hier richtest du optional den TMDB-Key ein, damit Poster zuverlässiger geladen werden.',
      'setup_step_3_title': '3. Keys unten eintragen und speichern',
      'setup_step_3_desc':
          'Danach lädt die App Metadaten und Poster direkt beim Tippen.',
      'omdb_setup_step_1':
          'Auf OMDb gehen, Name und E-Mail eingeben und als Use Case "Personal Use" eintragen.',
      'omdb_setup_step_2':
          'Formular abschicken. Du bekommst danach eine E-Mail mit deinem API-Key.',
      'omdb_setup_step_3':
          'Wichtig: In der E-Mail zusätzlich den Aktivierungslink anklicken.',
      'tmdb_setup_step_1': 'TMDB-Konto erstellen oder einloggen.',
      'tmdb_setup_step_2':
          'Auf "TMDB öffnen" tippen und auf der Seite nach unten scrollen.',
      'tmdb_setup_step_3':
          'Den API-Schlüssel kopieren (nicht den API Read Access Token).',
      'open_omdb': 'OMDb öffnen',
      'open_tmdb': 'TMDB öffnen',
      'omdb_section_title': 'OMDb (Metadaten & Ratings)',
      'tmdb_section_title': 'TMDB (Poster-Fallback)',
      'omdb_api_key': 'OMDb API-Key',
      'tmdb_api_key': 'TMDB API-Key (optional)',
      'omdb_api_hint':
          'Ohne API-Key können Poster, IMDb und Rotten Tomatoes nicht automatisch geladen werden.',
      'tmdb_api_hint':
          'Optional für Poster-Fallback. Ratings kommen weiterhin über OMDb.',
      'save_api_key': 'API-Key speichern',
      'test_key': 'Key testen',
      'testing_key': 'Teste Key...',
      'test_keys': 'Keys testen',
      'testing_keys': 'Teste Keys...',
      'omdb_key_valid': 'OMDb-Key ist gültig',
      'omdb_key_invalid': 'OMDb-Key ungültig oder leer',
      'omdb_key_invalid_tip':
          'Tipp: Prüfe die Aktivierung in der E-Mail. Der Key funktioniert erst nach Klick auf den Aktivierungslink.',
      'tmdb_key_valid': 'TMDB-Key ist gültig',
      'tmdb_key_invalid': 'TMDB-Key ungültig oder leer',
      'tmdb_key_invalid_tip':
          'Tipp: Verwende den API-Schlüssel (API Key), nicht den API Read Access Token.',
      'metadata_pick_title': 'Passenden Film auswählen',
      'metadata_pick_desc':
          'Mehrere Treffer gefunden. Bitte wähle den richtigen Film aus.',
      'cancel': 'Abbrechen',
      'close': 'Schließen',
      'link_open_error': 'Link konnte nicht geöffnet werden',
      'settings_saved': 'Einstellungen gespeichert',
      'movie_saved': 'Film gespeichert',
      'movie_duplicate_error':
          'Dieser Film ist bereits vorhanden und wurde nicht erneut gespeichert.',
      'delete_confirm_title': 'Film löschen?',
      'delete_confirm_message':
          'Möchtest du diesen Film wirklich aus deiner Liste entfernen?',
      'confirm_delete': 'Löschen',
      'change_rating': 'Ranking ändern',
      'share_no_imdb_link': 'Für diesen Film ist kein IMDb-Link verfügbar.',
      'auto_metadata_enabled': 'Metadaten automatisch laden',
      'auto_metadata_desc': 'Beim Tippen des Titels automatisch suchen',
      'external_ratings_enabled': 'IMDb/Rotten Tomatoes laden',
      'external_ratings_desc': 'Externe Bewertungen automatisch übernehmen',
      'editor_tab_auto': 'Automatisch',
      'editor_tab_rating': 'Bewertung',
      'editor_tab_entry': 'Eintrag',
      'entry_details_title': 'Dein Eintrag',
      'rating_details_title': 'Deine Bewertung',
      'add_details_title': 'Filmdetails',
      'rated_on_save_hint':
          'Zeitpunkt wird automatisch beim Speichern gesetzt.',
      'api_help': 'API-Key gibt es kostenlos auf omdbapi.com',
    },
    'en': {
      'movie_list_title': 'CineCue',
      'app_brand': 'CineCue',
      'welcome_subtitle':
          'Your movie journal with smart search, posters and fast ratings.',
      'welcome_note':
          'Setup takes around 2 minutes. After that, you can start right away.',
      'welcome_setup_cta': 'Set up',
      'tab_home': 'Home',
      'tab_watched': 'Already watched',
      'tab_discover': 'Add',
      'tab_discover_feed': 'Discover',
      'home_title': 'For You',
      'home_jump_search': 'Search',
      'home_popular_title': 'Most popular',
      'home_greeting_title': 'Hello, movie fan',
      'home_greeting_subtitle':
          'Search and log watched movies in just a few taps.',
      'home_search_hint': 'Search for a title...',
      'home_featured_label': 'Featured',
      'home_see_all': 'See all',
      'drawer_subtitle': 'Quick actions',
      'drawer_genres': 'Genres',
      'drawer_all_genres': 'All genres',
      'drawer_categories': 'Categories',
      'drawer_all_categories': 'All categories',
      'no_movies_yet': 'No movies added yet.',
      'add_movie': 'Add movie',
      'edit_movie': 'Edit movie',
      'save': 'Save',
      'title': 'Movie title',
      'comment': 'Comment',
      'choose_image': 'Choose custom image',
      'update_metadata': 'Load metadata',
      'personal_rating': 'Your rating',
      'imdb_rating': 'IMDb',
      'rotten_tomatoes': 'Rotten Tomatoes',
      'year': 'Year',
      'genre': 'Genre',
      'director': 'Director',
      'runtime': 'Runtime',
      'watched_on': 'Watched on',
      'watch_platform': 'Platform',
      'select_date': 'Pick date',
      'metadata_loading': 'Loading movie data...',
      'metadata_error': 'No data found for this title.',
      'metadata_hint': 'Type a title and auto-load metadata.',
      'metadata_missing_api_key':
          'Please add your OMDb API key in Settings first.',
      'metadata_tmdb_poster_only':
          'Poster loaded. Add an OMDb key as well for IMDb/Rotten Tomatoes.',
      'no_comment': 'No comment',
      'delete': 'Delete',
      'edit': 'Edit',
      'rating_desc': 'Rating high-low',
      'rating_asc': 'Rating low-high',
      'title_asc': 'Title A-Z',
      'category_asc': 'Category A-Z',
      'last_watched': 'Last rated',
      'sort_popularity_desc': 'Popularity high-low',
      'sort_popularity_asc': 'Popularity low-high',
      'sort_title_desc': 'Title Z-A',
      'settings': 'Settings',
      'dark_mode': 'Dark mode',
      'dark_mode_desc': 'Enable a dark color theme',
      'language': 'Language',
      'language_desc': 'Choose app language',
      'notifications': 'Notifications',
      'notifications_desc': 'Coming soon',
      'privacy_security': 'Privacy & Security',
      'privacy_settings': 'Coming soon',
      'help_support': 'Help & Support',
      'contact_us': 'Coming soon',
      'app_version': 'App version',
      'connected_success': 'Connected successfully',
      'login_failed': 'Login failed',
      'signed_out': 'Signed out successfully',
      'no_account_connected': 'No account connected',
      'connect': 'Connect',
      'disconnect': 'Sign out',
      'cloud_backup_title': 'Cloud backup',
      'cloud_backup_desc':
          'Back up your movies to Google Drive (private app data folder).',
      'cloud_backup_not_connected': 'No Google account connected',
      'cloud_backup_retention': 'Versions kept',
      'cloud_backup_threshold': 'Auto backup after changes',
      'cloud_backup_last_backup': 'Last backup',
      'cloud_backup_pending_changes': 'Pending changes',
      'cloud_backup_never': 'No backup yet',
      'cloud_backup_now': 'Backup now',
      'cloud_restore_latest': 'Restore latest backup',
      'cloud_auto_backup': 'Automatic backup',
      'cloud_auto_backup_desc':
          'Backs up after multiple changes and when leaving the app.',
      'cloud_auto_restore': 'Auto-restore on app launch',
      'cloud_auto_restore_desc': 'Only when there are no local movies yet.',
      'cloud_restore_confirm_title': 'Restore backup?',
      'cloud_restore_confirm_message':
          'Your local movie list will be replaced by the newest cloud backup.',
      'cloud_restore_confirm_action': 'Restore',
      'cloud_backup_not_signed_in': 'Please connect Google Drive first.',
      'cloud_backup_in_progress': 'Backup is already running.',
      'cloud_backup_db_missing': 'Local database file not found.',
      'cloud_backup_success': 'Backup uploaded successfully.',
      'cloud_backup_failed': 'Could not create backup.',
      'cloud_backup_no_backups': 'No cloud backup found.',
      'cloud_backup_integrity_failed':
          'Integrity check failed. Restore was cancelled.',
      'cloud_restore_success': 'Backup restored successfully.',
      'cloud_restore_failed': 'Could not restore backup.',
      'no_image': 'No image selected',
      'auto_data': 'Automatic data',
      'ratings': 'Ratings',
      'details': 'Details',
      'plot': 'Plot',
      'select_sort': 'Sort by',
      'catalog_panel_title': 'Discover movies',
      'catalog_panel_desc':
          'Search for movies and quickly add them to your watched list.',
      'catalog_search_hint': 'Search movie (e.g. Hangover)',
      'catalog_preview_hint': 'Tap a movie to review details before adding.',
      'catalog_missing_key':
          'Movie search requires an OMDb API key in Settings.',
      'catalog_open_settings': 'Open settings',
      'catalog_prompt': 'Type at least 2 characters to search for movies.',
      'catalog_searching': 'Searching...',
      'catalog_no_results': 'No matching movies found.',
      'catalog_add_button': 'Add',
      'catalog_open_details': 'Details',
      'catalog_already_added': 'Already added',
      'catalog_year_unknown': 'Year unknown',
      'catalog_loading_details': 'Loading movie details...',
      'catalog_add_from_details': 'Add to list',
      'catalog_duplicate_blocked':
          'This movie is already in your list and cannot be added twice.',
      'discover_feed_title': 'Movie inspiration',
      'discover_feed_desc':
          'Browse popular movies and add them directly to your list.',
      'discover_feed_loading': 'Loading suggestions...',
      'discover_feed_empty': 'No suggestions available.',
      'discover_feed_missing_key':
          'Add a TMDB API key in Settings to load suggestions.',
      'discover_feed_offline':
          'No connection. Please check your internet and try again.',
      'discover_feed_error': 'Could not load suggestions right now.',
      'retry': 'Retry',
      'watched_search_hint': 'Search watched movies',
      'seen_panel_title': 'Watched',
      'seen_panel_count_suffix': 'movies',
      'manual_add_movie': 'Add manually',
      'watchlist_title': 'Watchlist',
      'watchlist_empty': 'Your watchlist is currently empty.',
      'watchlist_subtitle': 'Saved for later',
      'watchlist_added': 'Added to watchlist.',
      'mark_as_watched': 'Mark as watched',
      'watchlist_sort_added': 'Recently added',
      'watchlist_sort_title': 'Title A-Z',
      'watchlist_sort_rating': 'Rating high-low',
      'category': 'Category',
      'category_hint': 'e.g. Want to rewatch',
      'category_wishlist': 'Want to watch',
      'category_favorite': 'Loved it',
      'category_rewatch': 'Want to rewatch',
      'category_manage_title': 'Custom categories',
      'category_manage_desc':
          'Create your own categories. They will appear in movie entry and filters.',
      'category_new_label': 'New category',
      'category_add': 'Add',
      'category_empty': 'No custom categories yet',
      'setup_wizard_title': 'Setup',
      'setup_intro_title': 'Quick setup',
      'setup_intro_desc':
          'In just a few minutes, the app can auto-load posters and extra ratings for your movies.',
      'setup_intro_local_only': 'Everything stays saved only on your device.',
      'setup_intro_omdb_info':
          'OMDb provides metadata plus IMDb and Rotten Tomatoes ratings.',
      'setup_intro_tmdb_info':
          'TMDB adds poster fallback when OMDb has no poster for a title.',
      'back': 'Back',
      'next': 'Next',
      'finish_setup': 'Finish',
      'setup_done': 'Setup completed',
      'metadata_settings_title': 'Movie metadata & ratings',
      'metadata_setup_title': 'Setup assistant',
      'metadata_setup_desc':
          'Set up your keys step by step. Your entries stay only in this app.',
      'start_setup': 'Start setup',
      'show_api_keys': 'Show keys',
      'hide_api_keys': 'Hide keys',
      'setup_step_1_title': '1. Create OMDb key',
      'setup_step_1_desc':
          'Set up your OMDb key so movie metadata and ratings can be loaded automatically.',
      'setup_step_2_title': '2. Optional: create TMDB key',
      'setup_step_2_desc':
          'Optional: set up TMDB so posters can be loaded more reliably.',
      'setup_step_3_title': '3. Paste keys below and save',
      'setup_step_3_desc':
          'After that, metadata and posters load automatically while typing.',
      'omdb_setup_step_1':
          'Open OMDb, enter your name/email and use "Personal Use" as the use case.',
      'omdb_setup_step_2':
          'Submit the form. You will get an email with your API key.',
      'omdb_setup_step_3':
          'Important: also click the activation link in that email.',
      'tmdb_setup_step_1': 'Create a TMDB account or sign in.',
      'tmdb_setup_step_2': 'Tap "Open TMDB" and scroll down on the page.',
      'tmdb_setup_step_3': 'Copy the API key (not the API Read Access Token).',
      'open_omdb': 'Open OMDb',
      'open_tmdb': 'Open TMDB',
      'omdb_section_title': 'OMDb (metadata & ratings)',
      'tmdb_section_title': 'TMDB (poster fallback)',
      'omdb_api_key': 'OMDb API key',
      'tmdb_api_key': 'TMDB API key (optional)',
      'omdb_api_hint':
          'Without an API key, posters, IMDb and Rotten Tomatoes cannot be loaded automatically.',
      'tmdb_api_hint':
          'Optional poster fallback. Ratings still come from OMDb.',
      'save_api_key': 'Save API key',
      'test_key': 'Test key',
      'testing_key': 'Testing key...',
      'test_keys': 'Test keys',
      'testing_keys': 'Testing keys...',
      'omdb_key_valid': 'OMDb key is valid',
      'omdb_key_invalid': 'OMDb key is invalid or empty',
      'omdb_key_invalid_tip':
          'Tip: Check the activation step in your email. The key works only after clicking the activation link.',
      'tmdb_key_valid': 'TMDB key is valid',
      'tmdb_key_invalid': 'TMDB key is invalid or empty',
      'tmdb_key_invalid_tip':
          'Tip: Use the API key, not the API Read Access Token.',
      'metadata_pick_title': 'Choose the correct movie',
      'metadata_pick_desc':
          'Multiple matches found. Please select the correct one.',
      'cancel': 'Cancel',
      'close': 'Close',
      'link_open_error': 'Could not open link',
      'settings_saved': 'Settings saved',
      'movie_saved': 'Movie saved',
      'movie_duplicate_error':
          'This movie already exists and was not saved again.',
      'delete_confirm_title': 'Delete movie?',
      'delete_confirm_message':
          'Do you really want to remove this movie from your list?',
      'confirm_delete': 'Delete',
      'change_rating': 'Change rating',
      'share_no_imdb_link': 'No IMDb link is available for this movie.',
      'auto_metadata_enabled': 'Auto-load metadata',
      'auto_metadata_desc': 'Search while typing the movie title',
      'external_ratings_enabled': 'Load IMDb/Rotten Tomatoes',
      'external_ratings_desc': 'Automatically apply external ratings',
      'editor_tab_auto': 'Auto',
      'editor_tab_rating': 'Rating',
      'editor_tab_entry': 'Entry',
      'entry_details_title': 'Your entry',
      'rating_details_title': 'Your rating',
      'add_details_title': 'Movie details',
      'rated_on_save_hint': 'Timestamp is set automatically when you save.',
      'api_help': 'Get a free API key on omdbapi.com',
    },
  };

  static String text(BuildContext context, String key) {
    final settings = AppSettingsScope.of(context);
    final language = settings.languageCode;
    return _translations[language]?[key] ?? _translations['en']![key] ?? key;
  }
}
